sciencecorp/synapse-api

api/status.proto
Primary use would be to indicate that a query failed not due to an internal error, but because the query was not able to find a valid result to return. The first use will be to indicate that impedance measurement of an electrode could not record an unsaturated waveform
=> Add status code to indicate a query was unable to return a valid result

api/nodes/spectral_filter.proto
Digital filtering requires the sampling frequency to properly calculate filter coefficients.
=> feat: Add sample rate field for filter node

api/node.proto, api/nodes/electrical_broadband.proto, api/nodes/electrical_stimulation.proto, api/nodes/stream_in.proto, api/nodes/stream_out.proto, api/status.proto
Add a new class of messages to report node-specific status information to the client. 
I have proposed this new group of messages as a follow-up to previous discussion in #11. The immediate application of these status messages is to report the LSB for an ElectricalBroadbandNode. Though I believe other nodes will benefit from having a dedicated place to report status information, and I have included an example for the StreamOut node. 
This PR is meant to be an initial proposal to get the ball rolling on discussion. If its agreed we should have status messages like this, I am happy to fill out initial examples for all other Nodes.
=> feat: Proposal for NodeStatus messages

api/query.proto
This adds a self-test query that can be used to return data about hardware calibration and health. An example test this query might be used for is validating a probe has all the correct register settings when it boots up.
The query message itself includes an optional field for specific electrode IDs to be used by self-tests that are conducted on specific electrodes. The response message (`SelfTestResponse`) contains a bool that is true if all tests passed. It then contains a list of `SelfTestItem` messages for each test procedure that was conducted. The `SelfTestItem` contains the name of the test, a boolean representing if the test passed, and a `test_data` field for more detailed data that the test may have collected. Finally, the `test_report` string can contain a message describing …
=> Add self-test query for device-specific health checks

api/logging.proto, api/synapse.proto
* Adds logging.proto
* Defines a log entry
* Defines requests for logs
* Adds GetLogs
* Adds TailLogs
* Should we discriminate on the timestamp source? I just use google's timestamp here, but we might want to describe if it is monotonic or system time (since the current SciFi device doesn't have persistent system time)
=> feature: Add logging endpoint for synapse devices

api/nodes/spectral_filter.proto
See discussion in #32 for the reasoning. This parameter will now be inferred from the upstream node in a signal chain.
=> Revert addition of filter sample rate

api/update.proto
Thinking about it more, we should really just use sha256 here instead of md5sum. The additional calculation is negligible and we don't get the vulnerabilities that md5 has.
=> fix: Use sha256 instead of md5sum

api/nodes/stream_out.proto
As we have discussed, multicast has its issues when streaming high bandwidth data over Wifi. We have tested unicast udp as an alternative transport with pretty good success. 
* Adds a specific UDP Multicast Configuration (for multicast if we ever want to support it again)
* Adds a Unicast UDP configuration. The client will tell the server which port and address to stream the data to
* bundles these in a transport option. we can extend this to different transports, like tcp, later
* CI passes.
=> feature: Add unicast udp transport to stream out

api/query.proto, api/synapse.proto
In order to achieve real time feedback on query, we add a stream option.
Note: the unary calls are left until we switch over completely as to not break backwards compatibility.
=> feature: add streamed query responses

api/status.proto, api/time.proto
In order to support synchronized time stamps in client and synapse devices, we support an NTP like TimeSyncPacket which allows for clock sync in software.
More details can be found here: https://en.wikipedia.org/wiki/Network_Time_Protocol#Clock_synchronization_algorithm
* Updates Status to include an optional time_sync_port to indicate time syncing capabilities
* added time.proto with the TimeSyncPacket 
* Tested with SciFi - was able to implement a client and server.
=> [feature] Add TimeSyncPacket to Synapse API to support software time synchronization

api/datatype.proto, api/node.proto, api/nodes/controller.proto
We are starting more BCI experiments that need flexbility in the output. So, add an output tensor message.
Also, add stubs for the ControllerNode concept. It is empty now, but it allows us to init a ControllerNode type. 
* Adds Tensor
* Adds Controller node type
- https://github.com/sciencecorp/synapse-python/pull/103
=> feat: Add controller node with output tensor

api/query.proto, api/synapse.proto, api/tap.proto
In this iteration, we focus on read taps that are connected under the hood using zmq. We allow users to list the endpoints that taps are being published from.
* Added tap.proto
- builds, being used for synapse devices.
=> feature: Read tap management

api/app.proto
We realized that the device configuration is duplicated, and can change between deployments/starts/stops. This minimizes the amount of information in the manifest. 
* removed device_configuration field. No one was using this api, so it does not break anything
- N/A
=> feature: Remove device configuration from app manifest

api/app.proto, api/synapse.proto
Right now app deployment involves using ssh and remote controlling the headstage OS; having an easily accessible shell like this substantially exposes the attack surface area and also is just less reliable.
* This PR adds a `DeployApp` method to the Synapse Control Plane API which allows the client to send the `.deb` file as a byte array, which will then be validated and installed atomically on the device side.
=> add app deployment to control plane api

api/nodes/application.proto
Application developers need a way to send generic application configuration. This provides that mechanism.
We can have users define a Protobuf message for their configuration like this:
```
message MyCustomParamters {
float value = 1;
string other = 2;
}
```
In C++, you can use it like this:
```c++
auto* app_config = node->mutable_application();
MyCustomParameters params;
params.set_value(12);
app_config->mutable_parameters()->PackFrom(params);
// Reading
const auto& params = app_config.parameters();
if (params.Is<MyCustomParameters>()) {
MyCustomParameters out_params;
params.UnpackTo(&out_params);
}
```
* Added parameters field to the ApplicationNodeConfig
- n/a
=> Feature: Add configuration struct to application config

api/tap.proto
We currently supported producers of data over a tap, now we need taps that can consume and listen to data. 
* Added a tap type
- n/a
Would like some feedback on the producer/consumer naming.
=> feature: add tap types to support producer and consumers

api/app.proto, api/device.proto, api/nodes/application.proto, api/synapse.proto
While conceptually nice, we revert the ability to pass Any as a parameter for app configs, and instead use the Struct. 
Any is tough because:
- We need to pass around the generated protobuf descriptors for each app to synapsectl (so we can deploy)
- We lose the ability to serialize to human readable json, the tools need to have the descriptors
If we move to structs we still get runtime type checking through GetXXXValue() methods. The main thing we lose with this is compile time safety.
* Provides a path to config schema, not generate protofiles
* Uses Struct instead of any
- Locally. Since this wasn't a release yet, we can re-use these fields without harm
=> Fix: use struct for configuration parameters

api/nodes/application.proto
Small change, but it seems like the Struct message type has some ergonomic issues, at least with our version of protobuf being used on the C++ side (e.g. field.count(key) doesn't actually return keys that are definitely there when iterating through the fields manually).
Might be a hint because they don't have docs on Structs: https://protobuf.dev/reference/cpp/cpp-generated/
* Swap out Struct for map
- Tested locally. Accessors work as expected.
=> fix: Fall back to map instead of struct

api/channel.proto, api/datatype.proto, api/nodes/signal_config.proto
We would like to support users to be able to record GPIO data with broadband data. These changes support that. This is in an effort to not have the clients care about timing at all - everything is in the same logical message with the same timestamp.
* Adds a channel range type to the BroadbandFrame. frame_data will be appended with aux data, indexed according to the message
* adds configuration options to the electrode config to configure ttl channels. leaves support for adc in the future as we get there. 
- builds, should be backwards compatible
=> Feature: Add support for recording from aux channels

api/channel.proto, api/datatype.proto
Sub "TTL" in favor for "GPIO". While there are nice connotations with the TTL acronym, it by definition is 5V (or 3.3V for LVTTL). 5V will kill current axon probes inputs. 
* s/TTL/GPIO/g
See: https://github.com/sciencecorp/headstage/pull/284
=> Rename TTL to GPIO

api/datatype.proto
For behavior reasons, we should keep track of unix timestamp with each broadband frame, as well as the time as calculated by the frames from the device. 
* Added unix timestamp field
* Updated comments
N/A
=> feature: add unix timestamp to the broadband frame data type

api/datatype.proto, api/nodes/optical_stimulation.proto
In order to support LED based stimulation, we need to define an optical stim frame. 
Biggest question is around the pixel representation. Does 0.0 -> 1.0 normalized intensity make sense? Or do we want to use an integer representation? Or flexibility with bytes and something like a PixelFormat enum
* Adds OpticalStimFrame
- builds
=> feature: Proposal for optical stim frame
